#!/usr/bin/env ruby

class ProjectCompletion
  def initialize(command)
    puts command.inspect
    @command = command
    @root_directory = root_directory
  end

  def matches
    projects.select do |task|
      task[0, typed.length] == typed
    end
  end

  def typed
    @command[/\s(.+?)$/, 1] || ''
  end

  def projects
    puts @root_directory.inspect
    `ls #{@root_directory}`.split
  end
end

puts ProjectCompletion.new(ENV["COMP_LINE"]).matches
exit 0
