#!/usr/bin/env ruby

class ProjectCompletion
  #Edit file with one line per root directory for auto project completion
  PROJECT_ROOTS_PATH = '~/.bash/completion_scripts/project_completion_roots'.freeze
  ROOT_PROJECTS_PATH = begin
    path = File.expand_path(PROJECT_ROOTS_PATH)
    path = File.readlink(path) if File.symlink?(path)
    path
  end.freeze
  ROOT_PROJECTS = begin
    if File.exists?(ROOT_PROJECTS_PATH)
      paths = File.open(ROOT_PROJECTS_PATH, 'r').readlines.collect(&:strip)
      Dir.glob(paths)
    else
      []
    end
  end.freeze
  PROJECTS = begin
    `ls -G #{ROOT_PROJECTS.join(' ')}`.split
  end.freeze

  def initialize(command)
    @command = command
  end

  def matches
    PROJECTS.select do |task|
      task[0, typed.length] == typed
    end
  end

  def typed
    @typed ||= @command[/\s(.+?)$/, 1] || ''
  end
end

puts ProjectCompletion.new(ENV["COMP_LINE"]).matches
exit 0
