#!/usr/bin/env ruby

class ProjectCompletion
  #Edit file with one line per root directory for auto project completion
  PROJECT_ROOTS_PATH = '~/.bash/completion_scripts/project_completion_roots'

  def initialize(command)
    @command = command
  end

  def matches
    projects.select do |task|
      task[0, typed.length] == typed
    end
  end

  def typed
    @command[/\s(.+?)$/, 1] || ''
  end

  def root_projects_path
    @path ||= File.expand_path(PROJECT_ROOTS_PATH)
    @path = File.readlink(path) if File.symlink?(@path)
    @path
  end

  def root_projects
    return [] unless File.exists?(root_projects_path)
    File.open(root_projects_path, 'r').readlines.collect do |path| 
      path.gsub(/\n\r?/,'').strip
    end.delete_if {|path| !File.exists?(path) }
  end

  def projects
    root_projects.inject([]) do |result, path|
      result += `ls #{path}`.split
    end
  end
end

puts ProjectCompletion.new(ENV["COMP_LINE"]).matches
exit 0
